apiVersion: v1
kind: Pod
metadata:
  name: my-pod
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
spec:
  serviceAccountName: default
  containers:
    - name: my-container
      image: bitnami/kubectl
      command: ["/bin/sh", "sleep 3600"]
      args:
        - "-c"
        - |
          #!/bin/sh
          # Create a directory to store the exported YAML files
          cd /tmp/
          mkdir -p exported-yaml
          # Loop through all namespaces in the cluster
          for namespace in $(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}'); do
          # Create a directory for each namespace
          mkdir -p "exported-yaml/$namespace"
          # Export YAML for all resources in the namespace
          for resource in $(kubectl get all,configmap,secret,serviceaccount,ingress,configmap -n $namespace -o name); do
          # Get the resource's YAML and save it to a file
          kubectl get -n $namespace -o yaml $resource > "exported-yaml/$namespace/$(basename $resource).yaml"
          done
          done
          echo "YAML resources exported and stored in the 'exported-yaml' directory."
      securityContext:
        runAsUser: 1000  # Specify a user with the necessary permissions
      restartPolicy: Never
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 15
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
